-- =====================================================================
-- Propósito : Sembrar el MODELO CANÓNICO v2 (entidades + campos) desde los
--             contratos de data-plane/canonico/entidades/*.yml.
-- Tablas    : metadatos.canonico_entidad, metadatos.canonico_campo
-- Alcance   : AGNÓSTICO — compartido por todos los tenants. El mapeo desde cada
--             ERP vive en los paquetes base (seeds 58 SAP B1, 59 Odoo).
-- Impacto   : bajo; catálogo de metadatos. No mueve datos.
-- Idempotente: sí (ON CONFLICT sobre las claves naturales).
-- Ref       : data-plane/canonico/DISENO-plata-oro.md §2
-- =====================================================================

-- ---------------------------------------------------------------- entidades
INSERT INTO metadatos.canonico_entidad (clave, nombre, dominio, tipo, descripcion) VALUES
  ('socio_negocio',       'Socio de negocio',      'datos_maestros', 'dimension',
   'Cliente Y proveedor unificados. Ambos ERPs los traen en una sola tabla; en Oro se separan en dim_cliente/dim_proveedor porque hay socios duales.'),
  ('producto',            'Producto',              'datos_maestros', 'dimension',
   'Producto o artículo. Reemplaza `item` del canónico v1 (sin mezcla de idioma).'),
  ('vendedor',            'Vendedor',              'datos_maestros', 'dimension',
   'Dimensión opcional: fuerte en SAP B1, débil en Odoo. Miembro default obligatorio.'),
  ('organizacion',        'Organización',          'datos_maestros', 'dimension',
   'Empresa/sociedad. Sin nivel sucursal: ninguna sociedad de Cresta lo usa (BPLId NULL).'),
  ('almacen',             'Almacén',               'datos_maestros', 'dimension',
   'Bodega. Sustituye al nivel sucursal: presente en 97.5% de las líneas de Proavisa.'),
  ('cuenta',              'Cuenta contable',       'finanzas',       'dimension',
   'Plan contable. PIEZA OBLIGATORIA: tipo_cuenta decide qué partida del mayor es cartera.'),
  ('centro_costo',        'Centro de costo',       'finanzas',       'dimension',
   'Uso opuesto entre tenants (99.8% en Cresta, casi nulo en Iron Network).'),
  ('moneda',              'Moneda',                'finanzas',       'dimension',
   'Monedas de la empresa. 49% del valor de compras de Cresta está en USD.'),
  ('tipo_cambio',         'Tipo de cambio',        'finanzas',       'dimension',
   'INFORMATIVO: los importes se toman ya convertidos del ERP, no se recalculan.'),
  ('documento_comercial', 'Documento comercial',   'ventas_compras', 'hecho_cabecera',
   'Cabecera de factura/nota de crédito. VENTA Y COMPRA unificadas por `flujo`.'),
  ('documento_linea',     'Línea de documento',    'ventas_compras', 'hecho_linea',
   'GRANO DEL HECHO. Solo líneas de producto (en Odoo hay que excluir impuesto y plazo de pago).'),
  ('partida_cartera',     'Partida de cartera',    'tesoreria',      'hecho_linea',
   'CxC y CxP desde el MAYOR, filtradas por tipo de cuenta. Nunca desde la factura.'),
  ('control_cuadre',      'Control de cuadre',     'gobierno',       'hecho_linea',
   'Compara el total del canónico contra el del ERP. Si no cuadra, Oro no publica.')
ON CONFLICT (clave) DO UPDATE
   SET nombre = EXCLUDED.nombre, dominio = EXCLUDED.dominio, tipo = EXCLUDED.tipo,
       descripcion = EXCLUDED.descripcion, actualizado_en = now();

-- ---------------------------------------------------------------- campos
INSERT INTO metadatos.canonico_campo (entidad_clave, nombre, tipo, requerido, descripcion, orden) VALUES
  -- socio_negocio
  ('socio_negocio','empresa_id','text',true,'Empresa (tenencia/RLS)',10),
  ('socio_negocio','socio_codigo','text',true,'Código del socio en el origen',20),
  ('socio_negocio','nombre','text',true,'Razón social / nombre',30),
  ('socio_negocio','nit','text',false,'Identificación tributaria',40),
  ('socio_negocio','es_cliente','boolean',true,'Actúa como cliente',50),
  ('socio_negocio','es_proveedor','boolean',true,'Actúa como proveedor',60),
  ('socio_negocio','grupo_codigo','text',false,'Grupo/categoría comercial',70),
  ('socio_negocio','condicion_pago_codigo','text',false,'Condición de pago pactada',80),
  ('socio_negocio','moneda_codigo','text',false,'Moneda habitual del socio',90),
  ('socio_negocio','pais','text',false,'País',100),
  ('socio_negocio','region','text',false,'Región/zona (posible eje de RLS)',110),
  ('socio_negocio','activo','boolean',false,'Socio activo en el origen',120),
  -- producto
  ('producto','empresa_id','text',true,'Empresa (RLS)',10),
  ('producto','producto_codigo','text',true,'Código del producto en el origen',20),
  ('producto','nombre','text',true,'Descripción del producto',30),
  ('producto','grupo_codigo','text',false,'Grupo/categoría de producto',40),
  ('producto','unidad_medida','text',false,'Unidad de medida base',50),
  ('producto','tipo_producto','text',false,'bien | servicio',60),
  ('producto','activo','boolean',false,'Producto activo',70),
  -- vendedor
  ('vendedor','empresa_id','text',true,'Empresa (RLS)',10),
  ('vendedor','vendedor_codigo','text',true,'Código de vendedor en el origen',20),
  ('vendedor','nombre','text',true,'Nombre del vendedor',30),
  ('vendedor','activo','boolean',false,'Vendedor activo',40),
  -- organizacion
  ('organizacion','empresa_id','text',true,'Identificador de la empresa (RLS)',10),
  ('organizacion','nombre','text',true,'Razón social de la empresa',20),
  ('organizacion','nit','text',false,'Identificación tributaria',30),
  ('organizacion','moneda_local','text',true,'Moneda funcional de la empresa',40),
  -- almacen
  ('almacen','empresa_id','text',true,'Empresa (RLS)',10),
  ('almacen','almacen_codigo','text',true,'Código de bodega en el origen',20),
  ('almacen','nombre','text',true,'Nombre de la bodega',30),
  ('almacen','activo','boolean',false,'Bodega activa',40),
  -- cuenta
  ('cuenta','empresa_id','text',true,'Empresa (RLS)',10),
  ('cuenta','cuenta_codigo','text',true,'Código de cuenta en el origen',20),
  ('cuenta','cuenta_codigo_visible','text',false,'Código legible del plan (SAP B1: FormatCode)',25),
  ('cuenta','nombre','text',true,'Nombre de la cuenta',30),
  ('cuenta','tipo_cuenta','text',true,'Tipo normalizado (por_cobrar, por_pagar, ingreso, ...)',40),
  ('cuenta','es_cartera_cobrar','boolean',true,'Cuenta por cobrar',50),
  ('cuenta','es_cartera_pagar','boolean',true,'Cuenta por pagar',60),
  ('cuenta','permite_conciliacion','boolean',false,'La cuenta se concilia por partida',70),
  ('cuenta','activa','boolean',false,'Cuenta no dada de baja',80),
  -- centro_costo
  ('centro_costo','empresa_id','text',true,'Empresa (RLS)',10),
  ('centro_costo','centro_costo_codigo','text',true,'Código en el origen',20),
  ('centro_costo','nombre','text',true,'Nombre del centro de costo',30),
  ('centro_costo','activo','boolean',false,'Centro de costo activo',40),
  -- moneda
  ('moneda','empresa_id','text',true,'Empresa (RLS)',10),
  ('moneda','moneda_codigo','text',true,'Código ISO de la moneda',20),
  ('moneda','nombre','text',false,'Nombre de la moneda',30),
  ('moneda','es_local','boolean',false,'Es la moneda funcional',40),
  -- tipo_cambio
  ('tipo_cambio','empresa_id','text',true,'Empresa (RLS)',10),
  ('tipo_cambio','moneda_codigo','text',true,'Moneda de la tasa',20),
  ('tipo_cambio','fecha','date',true,'Fecha de vigencia',30),
  ('tipo_cambio','tasa','numeric(18,6)',true,'Moneda local por unidad extranjera',40),
  -- documento_comercial
  ('documento_comercial','empresa_id','text',true,'Empresa (tenencia/RLS)',10),
  ('documento_comercial','documento_id','text',true,'Identificador interno en el origen',20),
  ('documento_comercial','documento_numero','text',false,'Número visible del documento',30),
  ('documento_comercial','flujo','text',true,'venta | compra',40),
  ('documento_comercial','tipo_documento','text',true,'factura | nota_credito',50),
  ('documento_comercial','tipo_documento_origen','text',false,'Tipo nativo del ERP',60),
  ('documento_comercial','documento_referencia','text',false,'Documento origen (NC → factura)',70),
  ('documento_comercial','referencia_externa','text',false,'Referencia del socio',80),
  ('documento_comercial','socio_codigo','text',true,'Cliente o proveedor según flujo',90),
  ('documento_comercial','vendedor_codigo','text',false,'Vendedor (relevante en venta)',100),
  ('documento_comercial','fecha_documento','date',true,'Fecha del documento (PUEDE ser futura)',110),
  ('documento_comercial','fecha_vencimiento','date',false,'Vencimiento pactado',120),
  ('documento_comercial','fecha_registro','date',false,'Fecha contable/fiscal',130),
  ('documento_comercial','moneda_documento','text',true,'Moneda de emisión',140),
  ('documento_comercial','moneda_local','text',false,'Moneda funcional',150),
  ('documento_comercial','tipo_cambio','numeric(18,6)',false,'Tasa aplicada por el ERP',160),
  ('documento_comercial','total_sin_impuesto_doc','numeric(18,4)',false,'Base, moneda del documento',170),
  ('documento_comercial','total_impuesto_doc','numeric(18,4)',false,'Impuesto, moneda del documento',180),
  ('documento_comercial','total_con_impuesto_doc','numeric(18,4)',false,'Total, moneda del documento',190),
  ('documento_comercial','total_sin_impuesto_local','numeric(18,4)',false,'Base, moneda local',200),
  ('documento_comercial','total_impuesto_local','numeric(18,4)',false,'Impuesto, moneda local',210),
  ('documento_comercial','total_con_impuesto_local','numeric(18,4)',true,'Total, moneda local',220),
  ('documento_comercial','total_descuento_local','numeric(18,4)',false,'Descuento total, moneda local',230),
  ('documento_comercial','saldo_documento_local','numeric(18,4)',false,'Saldo del documento — INFORMATIVO, no es la cartera',240),
  ('documento_comercial','estado','text',false,'abierto | cerrado',250),
  ('documento_comercial','estado_pago','text',false,'Estado de pago del ERP (informativo)',260),
  ('documento_comercial','creado_en','text',false,'Alta en el ERP (ventana incremental)',270),
  ('documento_comercial','actualizado_en','text',false,'Última modificación (ventana incremental)',280),
  -- documento_linea
  ('documento_linea','empresa_id','text',true,'Empresa (RLS)',10),
  ('documento_linea','documento_id','text',true,'Documento padre',20),
  ('documento_linea','linea_numero','integer',true,'Número de línea',30),
  ('documento_linea','flujo','text',true,'venta | compra (denormalizado)',40),
  ('documento_linea','tipo_documento','text',true,'factura | nota_credito (denormalizado)',50),
  ('documento_linea','fecha_documento','date',false,'Denormalizada de la cabecera',60),
  ('documento_linea','socio_codigo','text',false,'Cliente o proveedor (denormalizado)',70),
  ('documento_linea','vendedor_codigo','text',false,'Vendedor (denormalizado)',80),
  ('documento_linea','producto_codigo','text',false,'Producto de la línea',90),
  ('documento_linea','descripcion_linea','text',false,'Descripción libre',100),
  ('documento_linea','almacen_codigo','text',false,'Bodega de la línea',110),
  ('documento_linea','centro_costo_codigo','text',false,'Centro de costo (MULTIPLE si el origen reparte)',120),
  ('documento_linea','cuenta_codigo','text',false,'Cuenta contable de la línea',130),
  ('documento_linea','cantidad','numeric(18,4)',false,'Cantidad de la línea',140),
  ('documento_linea','unidad_medida','text',false,'Unidad de la línea',150),
  ('documento_linea','precio_unitario_doc','numeric(18,4)',false,'Precio unitario, moneda del documento',160),
  ('documento_linea','precio_antes_descuento','numeric(18,4)',false,'Precio antes de descuento',170),
  ('documento_linea','descuento_pct','numeric(18,6)',false,'Porcentaje de descuento del documento (sin acotar: el negocio usa descuentos muy grandes y casos especiales; es dato legítimo)',180),
  ('documento_linea','monto_sin_impuesto_doc','numeric(18,4)',false,'Base, moneda del documento',190),
  ('documento_linea','monto_impuesto_doc','numeric(18,4)',false,'Impuesto, moneda del documento',200),
  ('documento_linea','monto_con_impuesto_doc','numeric(18,4)',false,'Total línea, moneda del documento',210),
  ('documento_linea','monto_sin_impuesto_local','numeric(18,4)',true,'Base, moneda local',220),
  ('documento_linea','monto_impuesto_local','numeric(18,4)',false,'Impuesto, moneda local',230),
  ('documento_linea','monto_con_impuesto_local','numeric(18,4)',false,'Total línea, moneda local',240),
  ('documento_linea','monto_descuento_local','numeric(18,4)',false,'Descuento de la línea',250),
  ('documento_linea','costo_local','numeric(18,4)',false,'Costo (base del margen)',260),
  ('documento_linea','margen_local','numeric(18,4)',false,'Margen de la línea',270),
  ('documento_linea','moneda_documento','text',false,'Moneda del documento (denormalizada)',280),
  -- partida_cartera
  ('partida_cartera','empresa_id','text',true,'Empresa (tenencia/RLS)',10),
  ('partida_cartera','partida_id','text',true,'Identificador de la partida del mayor',20),
  ('partida_cartera','tipo_cartera','text',true,'cobrar | pagar',30),
  ('partida_cartera','socio_codigo','text',false,'Cliente (cobrar) o proveedor (pagar)',40),
  ('partida_cartera','cuenta_codigo','text',true,'Cuenta contable de la partida',50),
  ('partida_cartera','documento_origen','text',false,'Documento que originó la partida',60),
  ('partida_cartera','tipo_documento_origen','text',false,'Tipo nativo del documento origen',70),
  ('partida_cartera','origen_partida','text',false,'documento | asiento',80),
  ('partida_cartera','fecha_documento','date',false,'Fecha de la partida',90),
  ('partida_cartera','fecha_vencimiento','date',false,'BASE DEL AGING',100),
  ('partida_cartera','moneda_documento','text',false,'Moneda de la partida',110),
  ('partida_cartera','monto_original_doc','numeric(18,4)',false,'Monto original, moneda del documento',120),
  ('partida_cartera','monto_original_local','numeric(18,4)',false,'Monto original, moneda local',130),
  ('partida_cartera','saldo_pendiente_doc','numeric(18,4)',false,'Saldo abierto, moneda del documento',140),
  ('partida_cartera','saldo_pendiente_local','numeric(18,4)',true,'Saldo abierto, moneda local — LA MEDIDA',150),
  ('partida_cartera','esta_abierta','boolean',false,'La partida tiene saldo pendiente',160),
  ('partida_cartera','conciliada','boolean',false,'Partida totalmente conciliada',170),
  ('partida_cartera','descripcion_partida','text',false,'Memo de la línea del asiento',180),
  -- control_cuadre
  ('control_cuadre','empresa_id','text',true,'Empresa verificada',10),
  ('control_cuadre','concepto','text',true,'Qué se verifica',20),
  ('control_cuadre','fecha_corte','date',true,'Fecha de la verificación',30),
  ('control_cuadre','valor_erp','numeric(18,4)',true,'Total según el origen',40),
  ('control_cuadre','valor_canonico','numeric(18,4)',true,'Total según Plata',50),
  ('control_cuadre','diferencia','numeric(18,4)',true,'canónico − erp',60),
  ('control_cuadre','tolerancia','numeric(18,4)',true,'Umbral aceptado',70),
  ('control_cuadre','cuadra','boolean',true,'abs(diferencia) <= tolerancia',80)
ON CONFLICT (entidad_clave, nombre) DO UPDATE
   SET tipo = EXCLUDED.tipo, requerido = EXCLUDED.requerido,
       descripcion = EXCLUDED.descripcion, orden = EXCLUDED.orden,
       activo = true, actualizado_en = now();
